# WARNING: Do not deploy this configuration directly to a production environment
#
# The tutorial docker-compose files have not been written for production deployment and will not 
# scale. A proper architecture has been sacrificed to keep the narrative focused on the learning 
# goals, they are just used to deploy everything onto a single Docker machine. 
# They also contain various obvious security flaws - passwords in plain text, no load balancing,
# no use of HTTPS and so on. 
# 
# This is all to avoid the need of multiple machines, generating certificates, encrypting secrets
# and so on, purely so that a single docker-compose file can be read as an example to build on, 
# not use directly.  

version: "3"

services:

    # broker to communicate to deephub.io       
    tmppython:
        build: ./tmppython
        hostname: tmppython
        container_name: tmppython
        restart: unless-stopped
        environment:
        - TOKEN_URL=""
        - REQ_URL="" 
        - USERNAME=""
        - PASSWORD=""
        - MICROSERVICE_NAME="tmppython"
        - MICROSERVICE_VERSION="V1.0"
        networks:
            ot-link-net:

#Create internal link network for Containers
networks:
  ot-link-net:

#Create Volumes for persistent Storage
volumes:
  mosquittoLog:
  mosquittoData:
